# -*- coding: utf-8 -*-
"""cie1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eC6H0rbsE-9MwRpxLL1-WWBe39DSWYY-
"""

import pandas as pd
data=pd.read_csv("/content/mtcars.csv")
print(data)

import matplotlib.pyplot as plt
plt.hist(data['mpg'], bins=10, color='skyblue', edgecolor='black')
plt.title('Frequency Distribution of Miles per Gallon (mpg)')
plt.xlabel('Miles per Gallon (mpg)')
plt.ylabel('Frequency')
plt.grid()
plt.show()

import matplotlib.pyplot as plt
plt.scatter(data['wt'],data['mpg'],color='skyblue',alpha=0.5)
plt.title('relation between weight of the car and mpg')
plt.xlabel('Miles per Gallon (mpg)')
plt.ylabel('weight of the car')
plt.grid()
plt.show()

import matplotlib.pyplot as plt
tc=data.groupby('model').size().nlargest(5)
tc.plot(kind='bar',color='r')
plt.title('types of cars')
plt.xlabel('model')
plt.ylabel('frequency')
plt.grid()
plt.show()

import matplotlib.pyplot as plt
data.boxplot(column='mpg',by='cyl',color='r')
plt.title('boxplot')
plt.xlabel('mpg')
plt.ylabel('cyl')
plt.grid()
plt.show()